theme: jekyll-theme-hacker
#markdown: kramdown
#markdown: kramdown
jekyll-theme-hacker:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
  
markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - tables
    - strikethrough
    - superscript
    - with_to_data
