theme: jekyll-theme-hacker
#markdown: kramdown
#markdown: kramdown
#jekyll-theme-hacker:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
  
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighting: rouge

highlighter: rouge
